/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface ProxyInterface extends utils.Interface {
  functions: {
    "_addressStorage(string)": FunctionFragment;
    "_boolStorage(string)": FunctionFragment;
    "_bytesStorage(string)": FunctionFragment;
    "_initialized()": FunctionFragment;
    "_stringStorage(string)": FunctionFragment;
    "_uintStorage(string)": FunctionFragment;
    "addressToBankAccount(address)": FunctionFragment;
    "addressToLocks(address,uint256)": FunctionFragment;
    "globalTokenBalance(bytes32)": FunctionFragment;
    "owner()": FunctionFragment;
    "upgrade(address)": FunctionFragment;
    "whitelistedTokens(bytes32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "_addressStorage"
      | "_boolStorage"
      | "_bytesStorage"
      | "_initialized"
      | "_stringStorage"
      | "_uintStorage"
      | "addressToBankAccount"
      | "addressToLocks"
      | "globalTokenBalance"
      | "owner"
      | "upgrade"
      | "whitelistedTokens"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "_addressStorage",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "_boolStorage",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "_bytesStorage",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "_initialized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_stringStorage",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "_uintStorage",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "addressToBankAccount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "addressToLocks",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "globalTokenBalance",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "upgrade", values: [string]): string;
  encodeFunctionData(
    functionFragment: "whitelistedTokens",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "_addressStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_boolStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_bytesStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_initialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_stringStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_uintStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addressToBankAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addressToLocks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "globalTokenBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "upgrade", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "whitelistedTokens",
    data: BytesLike
  ): Result;

  events: {
    "ClaimedTokens(address,uint256,bytes32,uint256)": EventFragment;
    "LockCreated(address,address,bytes32,uint256,uint32,uint32)": EventFragment;
    "TokensDeposit(address,bytes32,uint256)": EventFragment;
    "TokensTransfer(address,address,bytes32,uint256)": EventFragment;
    "TokensWithdraw(address,bytes32,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ClaimedTokens"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LockCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokensDeposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokensTransfer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokensWithdraw"): EventFragment;
}

export interface ClaimedTokensEventObject {
  _sender: string;
  numberOfGivenLock: BigNumber;
  _symbol: string;
  _amount: BigNumber;
}
export type ClaimedTokensEvent = TypedEvent<
  [string, BigNumber, string, BigNumber],
  ClaimedTokensEventObject
>;

export type ClaimedTokensEventFilter = TypedEventFilter<ClaimedTokensEvent>;

export interface LockCreatedEventObject {
  _sender: string;
  _recipient: string;
  _symbol: string;
  _amount: BigNumber;
  _startTime: number;
  _endTime: number;
}
export type LockCreatedEvent = TypedEvent<
  [string, string, string, BigNumber, number, number],
  LockCreatedEventObject
>;

export type LockCreatedEventFilter = TypedEventFilter<LockCreatedEvent>;

export interface TokensDepositEventObject {
  _sender: string;
  _symbol: string;
  _amount: BigNumber;
}
export type TokensDepositEvent = TypedEvent<
  [string, string, BigNumber],
  TokensDepositEventObject
>;

export type TokensDepositEventFilter = TypedEventFilter<TokensDepositEvent>;

export interface TokensTransferEventObject {
  _sender: string;
  _recipient: string;
  _symbol: string;
  _amount: BigNumber;
}
export type TokensTransferEvent = TypedEvent<
  [string, string, string, BigNumber],
  TokensTransferEventObject
>;

export type TokensTransferEventFilter = TypedEventFilter<TokensTransferEvent>;

export interface TokensWithdrawEventObject {
  _sender: string;
  _symbol: string;
  _amount: BigNumber;
}
export type TokensWithdrawEvent = TypedEvent<
  [string, string, BigNumber],
  TokensWithdrawEventObject
>;

export type TokensWithdrawEventFilter = TypedEventFilter<TokensWithdrawEvent>;

export interface Proxy extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ProxyInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    _addressStorage(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    _boolStorage(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    _bytesStorage(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    _initialized(overrides?: CallOverrides): Promise<[boolean]>;

    _stringStorage(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    _uintStorage(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    addressToBankAccount(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, boolean] & {
        createdAt: BigNumber;
        totalBalance: BigNumber;
        availableBalance: BigNumber;
        lockedBalance: BigNumber;
        transactionsCount: BigNumber;
        isActive: boolean;
      }
    >;

    addressToLocks(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        startTime: BigNumber;
        endTime: BigNumber;
        lockedValue: BigNumber;
        unlockedValue: BigNumber;
        claimed: BigNumber;
      }
    >;

    globalTokenBalance(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    upgrade(
      _newAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    whitelistedTokens(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  _addressStorage(arg0: string, overrides?: CallOverrides): Promise<string>;

  _boolStorage(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  _bytesStorage(arg0: string, overrides?: CallOverrides): Promise<string>;

  _initialized(overrides?: CallOverrides): Promise<boolean>;

  _stringStorage(arg0: string, overrides?: CallOverrides): Promise<string>;

  _uintStorage(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  addressToBankAccount(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, boolean] & {
      createdAt: BigNumber;
      totalBalance: BigNumber;
      availableBalance: BigNumber;
      lockedBalance: BigNumber;
      transactionsCount: BigNumber;
      isActive: boolean;
    }
  >;

  addressToLocks(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
      startTime: BigNumber;
      endTime: BigNumber;
      lockedValue: BigNumber;
      unlockedValue: BigNumber;
      claimed: BigNumber;
    }
  >;

  globalTokenBalance(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  upgrade(
    _newAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  whitelistedTokens(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    _addressStorage(arg0: string, overrides?: CallOverrides): Promise<string>;

    _boolStorage(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    _bytesStorage(arg0: string, overrides?: CallOverrides): Promise<string>;

    _initialized(overrides?: CallOverrides): Promise<boolean>;

    _stringStorage(arg0: string, overrides?: CallOverrides): Promise<string>;

    _uintStorage(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    addressToBankAccount(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, boolean] & {
        createdAt: BigNumber;
        totalBalance: BigNumber;
        availableBalance: BigNumber;
        lockedBalance: BigNumber;
        transactionsCount: BigNumber;
        isActive: boolean;
      }
    >;

    addressToLocks(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        startTime: BigNumber;
        endTime: BigNumber;
        lockedValue: BigNumber;
        unlockedValue: BigNumber;
        claimed: BigNumber;
      }
    >;

    globalTokenBalance(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    upgrade(_newAddress: string, overrides?: CallOverrides): Promise<void>;

    whitelistedTokens(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "ClaimedTokens(address,uint256,bytes32,uint256)"(
      _sender?: string | null,
      numberOfGivenLock?: null,
      _symbol?: BytesLike | null,
      _amount?: null
    ): ClaimedTokensEventFilter;
    ClaimedTokens(
      _sender?: string | null,
      numberOfGivenLock?: null,
      _symbol?: BytesLike | null,
      _amount?: null
    ): ClaimedTokensEventFilter;

    "LockCreated(address,address,bytes32,uint256,uint32,uint32)"(
      _sender?: string | null,
      _recipient?: string | null,
      _symbol?: BytesLike | null,
      _amount?: null,
      _startTime?: null,
      _endTime?: null
    ): LockCreatedEventFilter;
    LockCreated(
      _sender?: string | null,
      _recipient?: string | null,
      _symbol?: BytesLike | null,
      _amount?: null,
      _startTime?: null,
      _endTime?: null
    ): LockCreatedEventFilter;

    "TokensDeposit(address,bytes32,uint256)"(
      _sender?: string | null,
      _symbol?: BytesLike | null,
      _amount?: BigNumberish | null
    ): TokensDepositEventFilter;
    TokensDeposit(
      _sender?: string | null,
      _symbol?: BytesLike | null,
      _amount?: BigNumberish | null
    ): TokensDepositEventFilter;

    "TokensTransfer(address,address,bytes32,uint256)"(
      _sender?: string | null,
      _recipient?: string | null,
      _symbol?: BytesLike | null,
      _amount?: null
    ): TokensTransferEventFilter;
    TokensTransfer(
      _sender?: string | null,
      _recipient?: string | null,
      _symbol?: BytesLike | null,
      _amount?: null
    ): TokensTransferEventFilter;

    "TokensWithdraw(address,bytes32,uint256)"(
      _sender?: string | null,
      _symbol?: BytesLike | null,
      _amount?: BigNumberish | null
    ): TokensWithdrawEventFilter;
    TokensWithdraw(
      _sender?: string | null,
      _symbol?: BytesLike | null,
      _amount?: BigNumberish | null
    ): TokensWithdrawEventFilter;
  };

  estimateGas: {
    _addressStorage(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _boolStorage(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    _bytesStorage(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    _initialized(overrides?: CallOverrides): Promise<BigNumber>;

    _stringStorage(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    _uintStorage(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    addressToBankAccount(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addressToLocks(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    globalTokenBalance(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    upgrade(
      _newAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    whitelistedTokens(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    _addressStorage(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _boolStorage(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _bytesStorage(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _initialized(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _stringStorage(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _uintStorage(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addressToBankAccount(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addressToLocks(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    globalTokenBalance(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    upgrade(
      _newAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    whitelistedTokens(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
